### ISSUE TITLE
漫画章节加载失败 exception  builder  error  invalid port number

### ISSUE THREAD

**Issue by zhaohansprt** [Hentioe/mikack-mobile#172]
古风漫画网   －狂王 西行纪前传
快看漫画   －唐人街小先生
所有章节都加载失败  必现bug

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Hentioe** [comment]
好的，感谢提交。我会尽快测试一下，请等待后续回复。

**Comment by Hentioe** [comment]
古风漫画网的两个都被删除了，但是章节列表还保留着在（无实际章节链接）。所以这不是 bug，但不排除未来会将这种已屏蔽的内容故意返回空章节的可能。

唐人街小先生在快看漫画上搜索不到，你能给下链接吗。

**Comment by Hentioe** [comment]
快看漫画阅读问题已在 `0.7.1-1` 版本修复，古风漫画网是上游自身的问题，暂且不做特殊处理。
