### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by yanguiSV0** [Hentioe/mikack-mobile#182]
一搜索就闪退，我靠

**Comment by Hentioe** [comment]
这类项目要经常维护才能保持可用性。三年未有更新了，很明显已经不能用了。在未来我可能会重启这个项目，但不是现在。所以建议你不要使用，直接卸载。（你可以给这个项目点 Watch，能收到更新的通知）

**Comment by yanguiSV0** [comment]
> 这类项目要经常维护才能保持可用性。三年未有更新了，很明显已经不能用了。在未来我可能会重启这个项目，但不是现在。所以建议你不要使用，直接卸载。（你可以给这个项目点 Watch，能收到更新的通知）

好的

**Comment by Z-fly** [comment]
还会更新吗
